Algoritmo "semnome"
// Disciplina  : UC9 ALGORITMOS
// Professor   : Rodrigo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Michele
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 
nome: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Qual é o seu nome: ")
leia (nome)
escreva ("Olá, ", nome, ", é um prazer te conhecer!")


Fimalgoritmo