Algoritmo "semnome"

// Disciplina : ALGORITMOS
// Professor : Rodrigo
// Descrição   :40) Crie um aplicativo que mostre na tela a seguinte contagem:
//             0 3 6 9 12 15 18 Acabou!

// Autor(a)    : michele
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis
n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
n<-0
enquanto n<=18 faça
escreva (n:3)
n<-n+3
fimenquanto
escreva ("   Acabou!")
Fimalgoritmo